name: Build Plugin

on:
  pull_request:
  push:
    branches:
      - "**"
      - "!develop"
      - "!master"
    tags-ignore:
      - "**"

jobs:
  build-plugin:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm i -g typescript ts-node
      - run: tsc -v ; ts-node -v
      - run: npm ci
      - run: npm run build
      - run: docker run -td -p 15672:15672 -p 5672:5672 --name RABBITMQBSBTEST -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest rabbitmq:3-management
      - run: npm run test

      - name: Test Report ${{ matrix.node-version }}
        uses: dorny/test-reporter@v1.5.0
        with:
          name: Tests
          path: junit.json
          reporter: mocha-json

      - name: Upload coverage reports to Codecov
        if: contains(matrix.node-version, '18.x')
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage

      - name: cleanup
        if: always()
        run: rm -f ~/.npmrc ; rm -f ./.npmrc;

      - name: cleanup docker
        if: always()
        run: docker rm -f RABBITMQBSBTEST

  #docs_build_:
  #  runs-on: ubuntu-latest
  #
  #  strategy:
  #    matrix:
  #      node-version: [16.x]
  #      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  #
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v3
  #      with:
  #        fetch-depth: 0
  #
  #    - name: Use Node.js ${{ matrix.node-version }}
  #      uses: actions/setup-node@v3
  #      with:
  #        node-version: ${{ matrix.node-version }}
  #        cache: "npm"
  #
  #    - run: npm ci
  #      working-directory: documentation/
  #
  #    - run: npm run build
  #      working-directory: documentation/
